# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/blockchainbankdatabase
spring.datasource.username=postgres
spring.datasource.password=user

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# application.properties
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=deleted
server.ssl.key-store-type=PKCS12

# Force TLS 1.2 and 1.3 only (disable older versions)
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
server.port=8443
